### ISSUE TITLE
`direnv allow` asks to start watcher/daemon when project has not yet built

### ISSUE THREAD

**Issue by IvanMalison** [target/lorri#113] opened 2019-07-01 23:22 UTC
When enabling an .envrc that uses lorri for some shell.nix which has not yet actually been executed, lorri will output:

```
Please start `lorri daemon` or run `lorri watch` before using direnv integration.
```

even when the lorri daemon is running. This seems to happen only when a build has not yet completed for the relevant directory, which makes sense. lorri is probably only checking for some cached nix shell and because it does not exist it decides to output this message. The behavior is still likely to be confusing for the end user though.

I'm not sure what the best thing to do in this scenario is (Is there an easy way to talk to the daemon and ask if it has a build current taking place for the current directory?).

**Comment by grahamc** [comment] 2019-09-26 15:31
#151 is a dupe of this.

**Closed** 2019-09-26 16:06 UTC
Labels: P2, bug, user-facing
