### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by grahamc** [target/lorri#306] opened 2020-01-29 13:50 UTC

**Comment by curiousleo** [comment] 2020-01-29 15:38
Related: https://github.com/target/lorri/issues/269

**Comment by curiousleo** [comment] 2020-01-29 15:52
Does "1.0" mean we're ditching the "number of commits" version scheme that's currently built into `release.nix` and `lorri upgrade`?
Also see https://github.com/target/lorri/issues/269#issuecomment-579822694

**Comment by grahamc** [comment] 2020-01-29 15:53
I think we should keep those numbers, and also add a real version number. Is that silly?

**Comment by curiousleo** [comment] 2020-01-29 16:03
> I think we should keep those numbers, and also add a real version number. Is that silly?

I think that has the potential to confuse users. My radical proposal for this would be:
- remove `lorri upgrade` and changelog parsing; I don't think we need it
- take `release.nix` and turn it into a `CHANGELOG.md` with entries for the so-far released versions `unstable-2019-10-30` and `unstable-2020-01-09`
- from this point on, update `CHANGELOG.md` like a conventional changelog, [e.g. this one](https://github.com/BurntSushi/ripgrep/blob/master/CHANGELOG.md).

**Comment by Profpatsch** [comment] 2020-01-29 20:51
>     * remove `lorri upgrade` and changelog parsing; I don't think we need it

I use it regularly to update lorri to current master, it’s great (also for trying out in-progress branches once https://github.com/target/lorri/pull/168 is merged)

**Comment by Profpatsch** [comment] 2020-01-29 20:55
Apart from that we should make an effort to check that every part of the command line is as stable as possible, and what parts of the command line are intended for machine-readable output; e.g. we wouldn’t want people to start parsing the output of `lorri info` or even `lorri watch`.

**Comment by curiousleo** [comment] 2020-01-30 08:02
> I use it regularly to update lorri to current master, it’s great (also for trying out in-progress branches once #168 is merged)

I think we've discussed this before - you use `lorri self-upgrade`, I don't (`git checkout <branch> && nix-build .` works well enough for me), therefore I see it mainly as something that increases the cost of maintaining lorri whereas you see it as something that adds value. I don't see a way towards a consensus on this.

**Comment by curiousleo** [comment] 2020-01-30 08:04
> Apart from that we should make an effort to check that every part of the command line is as stable as possible, and what parts of the command line are intended for machine-readable output; e.g. we wouldn’t want people to start parsing the output of `lorri info` or even `lorri watch`.

Yes. It's a bit unfortunate that this discussion is happening on two issues at once -- also see https://github.com/target/lorri/issues/269#issuecomment-579822694:

> We could adopt semantic versioning here, in which case we would need to define precisely what "incompatible change" means for lorri in terms of subcommands, arguments, outputs and behaviour.

And yes, it would be useful to make the distinction between subcommands meant for machines and those made for humans. The former would have to have stricter compatibility guarantees.

**Comment by curiousleo** [comment] 2020-01-30 08:10
@grahamc any reason this ticket is called "Release 1.0" and not "Release 1.0.0"? The latter would lend itself better to a semantic-ish versioning scheme.

@Profpatsch what's your take on the versioning scheme - say we keep `lorri self-upgrade`, which enforces the "revCount" version, should we have a semantic-ish versioning scheme (starting from 1.0[.0]) alongside it?

**Comment by Profpatsch** [comment] 2020-01-30 14:37
>  you use `lorri self-upgrade`, I don't (`git checkout <branch> && nix-build .` works well enough for me), therefore I see it mainly as something that increases the cost of maintaining lorri whereas you see it as something that adds value.

https://github.com/target/lorri/pull/168 was intended as a way to more easily get people to test out changes, so they don’t have to check out the repository and switch to the right branch and build and install. It also eases maintenance.
I don’t know how exactly it adds maintenance overhead, it’s fairly static code that shouldn’t change very often.

**Comment by Profpatsch** [comment] 2020-01-30 14:40
> @Profpatsch what's your take on the versioning scheme - say we keep `lorri self-upgrade`, which enforces the "revCount" version

I don’t think `lorri self-upgrade` strictly *needs* to enforce `revCount`. We can just inject the branch name and the git revision, plus maybe the release version it is based on.

**Comment by Profpatsch** [comment] 2020-01-30 14:43
So, what I’m saying is let’s remove the changelog stuff from `self-upgrade` if it’s too much hassle to maintain and just make it into a very simple way to install a specific version.

**Comment by curiousleo** [comment] 2020-02-04 15:54
To do (also see https://github.com/target/lorri/blob/master/MAINTAINERS.md#publishing-a-release-on-nixpkgs):
- [x] Bump version in Cargo.toml
   PR: https://github.com/target/lorri/pull/323
- [ ] Tag release at 88c680c9abf0f04f2e294436d20073ccf26f0781
   ```
   $ git tag 1.0 88c680c9abf0f04f2e294436d20073ccf26f0781 && \
     git push origin 1.0
   ```
- [ ] Release to `nixos-unstable`
- [ ] Release to `nixos-19.09`

**Comment by Profpatsch** [comment] 2020-03-03 11:08
Everything’s done, closing.

**Closed by Profpatsch** 2020-03-03 11:08 UTC
