### ISSUE TITLE
Improve error message when shell.nix is failing

### ISSUE THREAD

**Issue by jfroche** [target/lorri#143] opened 2019-08-30 12:13 UTC
having 
```
with import <nixpkgs> {};
pkgs.mkShell {
  buildInputs = [
    foobar
  ];
}
```

we run `RUST_BACKTRACE=full lorri watch`
we get:

```
Started
thread '<unnamed>' panicked at 'got more or less than one build product from logged_evaluation.nix: []', src/builder.rs:89:5
stack backtrace:
   0:     0x55b97cd7ddcf - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hca90a656f82f7090
   1:     0x55b97cd8d517 - std::sys_common::backtrace::print::hc0f09baa317c9c13
   2:     0x55b97cd828b3 - std::panicking::default_hook::{{closure}}::h8b932dda5d5aa5fb
   3:     0x55b97cd82640 - std::panicking::default_hook::h73f0283673f071f7
   4:     0x55b97cd82faf - std::panicking::rust_panic_with_hook::hfb62954e8a2422c3
   5:     0x55b97cd82b41 - std::panicking::continue_panic_fmt::hdc6f6763fa99ff03
   6:     0x55b97cd82a8e - std::panicking::begin_panic_fmt::h652121450219d0d4
   7:     0x55b97cc34a07 - lorri::builder::run::hbb8cf3e23413aecf
   8:     0x55b97cc5667b - lorri::build_loop::BuildLoop::once::hfbc08a3947497490
   9:     0x55b97cc563af - lorri::build_loop::BuildLoop::forever::h50ddf3e10f88b5cc
  10:     0x55b97cc38b3f - std::sys_common::backtrace::__rust_begin_short_backtrace::h6430451947a1ce36
  11:     0x55b97cc2e6c8 - std::panicking::try::do_call::h383385312a0ac4e8
  12:     0x55b97cd97ab9 - __rust_maybe_catch_panic
  13:     0x55b97cc3f874 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9362940600f79da0
  14:     0x55b97cd7b4be - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hc3a444b8803cf943
  15:     0x55b97cd8217f - std::sys_common::thread::start_thread::hb1320f6edf722579
  16:     0x55b97cd7e9a5 - std::sys::unix::thread::Thread::new::thread_start::hc0c954f6a39d0e2e
  17:     0x7f7f85405ef6 - start_thread
  18:     0x7f7f8512522e - __GI___clone
  19:                0x0 - <unknown>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:999:5
stack backtrace:
   0:     0x55b97cd7ddcf - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hca90a656f82f7090
   1:     0x55b97cd8d517 - std::sys_common::backtrace::print::hc0f09baa317c9c13
   2:     0x55b97cd828b3 - std::panicking::default_hook::{{closure}}::h8b932dda5d5aa5fb
   3:     0x55b97cd82640 - std::panicking::default_hook::h73f0283673f071f7
   4:     0x55b97cd82faf - std::panicking::rust_panic_with_hook::hfb62954e8a2422c3
   5:     0x55b97cd82b41 - std::panicking::continue_panic_fmt::hdc6f6763fa99ff03
   6:     0x55b97cd82a25 - rust_begin_unwind
   7:     0x55b97cdaf63c - core::panicking::panic_fmt::h95972081a9687957
   8:     0x55b97cc1f564 - core::result::unwrap_failed::h8210ba461eea6f78
   9:     0x55b97cc4a9ea - lorri::ops::watch::main::h14a6e1cd3d0c3889
  10:     0x55b97cc13e26 - lorri::main::h49ee70582fd361cb
  11:     0x55b97cc14522 - std::rt::lang_start::{{closure}}::h5d980ca3d7334c06
  12:     0x55b97cd829c2 - std::panicking::try::do_call::h58dd4f747553ff5f
  13:     0x55b97cd97ab9 - __rust_maybe_catch_panic
  14:     0x55b97cd932c8 - std::rt::lang_start_internal::hd752bd0add31c5fb
  15:     0x55b97cc144f4 - main
  16:     0x7f7f85054b8d - __libc_start_main
  17:     0x55b97cc132c9 - _start
  18:                0x0 - <unknown>
```
maybe we could to give a more user friendly message to the user ?

**Comment by Profpatsch** [comment] 2019-09-02 12:35
This is a temporary regression on master, because we merged #135, which is part of the way to #117 (still in review), which fixes this issue.

So instead of `master`, I recommend either using the `rolling-release` branch (which is our release branch) or checking out `builder-add-transitive-source-detection-tests` for now.

**Closed** 2019-10-18 19:15 UTC
Labels: bug
