### ISSUE TITLE
Error in lorri-keep-env-hack-*.drv when shellHook returns non-zero

### ISSUE THREAD

**Issue by haslersn** [target/lorri#264] opened 2019-12-29 17:37 UTC
The following `shell.nix` **works with nix-shell** but doesn't work with lorri for the reason stated in the title above.

```nix
(import <nixpkgs> {}).stdenv.mkDerivation {
  name = "shell";
  shellHook = ''
    echo foo
    $(exit 1)
  '';
}
```

`lorri watch` yields:

```
[...]
            "these derivations will be built:",
            "  /nix/store/bq4f2as76d9hxvsz7afghn27n7lx8fwk-lorri-keep-env-hack-shell.drv",
            "building \'/nix/store/bq4f2as76d9hxvsz7afghn27n7lx8fwk-lorri-keep-env-hack-shell.drv\'...",
            "foo",
            "builder for \'/nix/store/bq4f2as76d9hxvsz7afghn27n7lx8fwk-lorri-keep-env-hack-shell.drv\' failed with exit code 1",
            "error: build of \'/nix/store/bq4f2as76d9hxvsz7afghn27n7lx8fwk-lorri-keep-env-hack-shell.drv\' failed",
        ],
    },
)
```

**Comment by curiousleo** [comment] 2020-01-06 09:15
Hi @haslersn!

```console
$ nix-shell
foo
$ echo $?
1
```

The exit code of `nix-shell` is 1, i.e. it indicates failure - and rightly so. I'm not sure exactly what you mean by "works with nix-shell" in this context.

I appreciate the minimal repro shell.nix, but is there a real-world use case that would help us understand the problem better? It seems to me that both lorri and nix-shell _should_ fail is the shell hook fails (i.e. returns a non-zero exit code), which they do.

Perhaps the issue is that the error message

> build of \'/nix/store/bq4f2as76d9hxvsz7afghn27n7lx8fwk-lorri-keep-env-hack-shell.drv\' failed

could be more specific?

**Comment by haslersn** [comment] 2020-01-06 09:50
> Hi @haslersn!
> 
> ```
> $ nix-shell
> foo
> $ echo $?
> 1
> ```
> 
> The exit code of `nix-shell` is 1, i.e. it indicates failure - and rightly so.

No. That's not the exit code of `nix-shell`, because `nix-shell` has not even terminated yet. It's just the exit code of the `shellHook`.

I had a use case where lorri didn't work in our project because of this bug.

`nix-shell` allows shellHook with exit code 1 and I understand lorri as a `nix-shell` replacememt.

**Comment by curiousleo** [comment] 2020-01-06 11:32
`nix-build` runs `set +e` before running the shell hook; lorri currently does not.

https://github.com/NixOS/nix/blob/2.3.1/src/nix-build/nix-build.cc#L422

**Comment by curiousleo** [comment] 2020-01-06 11:40
Bump for https://github.com/target/lorri/issues/95

**Comment by curiousleo** [comment] 2020-01-10 09:40
I would like to close this issue in favour of https://github.com/target/lorri/issues/273, which is more actionable. See https://github.com/target/lorri/pull/265 for a discussion of why we don't want to ignore command failures in shellHook in lorri.

**Closed** 2020-01-13 13:34 UTC
