### ISSUE TITLE
Error in lorri-keep-env-hack with vulkan-validation-layers as buildInput

### ISSUE THREAD

**Issue by HappyEnt** [target/lorri#262] opened 2019-12-22 00:31 UTC
Hello,

creating a shell with vulkan-validation-layers as input fails for me when building with lorri:
```nix
let
  pkgs = import <nixpkgs> {};
in
  pkgs.mkShell {
    buildInputs = with pkgs; [
      vulkan-validation-layers
    ];
  }
```

This is the relevant error output generated by lorri:
```
"instantiated \'vulkan-validation-layers-1.1.114.0\' -> \'/nix/store/6in5fii43cwzjb2wk5wc2pdk0wbvsvbg-vulkan-validation-layers-1.1.114.0.drv\'",
"evaluating file \'/nix/store/pkj2rnlnpvck4s9b3sxlfvy7pfc7bknq-closure.nix\'",
"instantiated \'lorri-keep-env-hack-nix-shell\' -> \'/nix/store/qrmdx67c9ppyhkicl04a18nwpjj284ll-lorri-keep-env-hack-nix-shell.drv\'",
"these derivations will be built:",
"  /nix/store/qrmdx67c9ppyhkicl04a18nwpjj284ll-lorri-keep-env-hack-nix-shell.drv",
"building \'/nix/store/qrmdx67c9ppyhkicl04a18nwpjj284ll-lorri-keep-env-hack-nix-shell.drv\'...",
"/nix/store/yy5v1i5zym74an5ays78kmlnpvvrvz0n-vulkan-validation-layers-1.1.114.0/nix-support/setup-hook: line 1: XDG_DATA_DIRS: unbound variable",
"builder for \'/nix/store/qrmdx67c9ppyhkicl04a18nwpjj284ll-lorri-keep-env-hack-nix-shell.drv\' failed with exit code 1",
"error: build of \'/nix/store/qrmdx67c9ppyhkicl04a18nwpjj284ll-lorri-keep-env-hack-nix-shell.drv\' failed",
```
Dropping into an environment with nix-shell works flawlessly.

lorri 0.1.0
nix (Nix) 2.3.1

**Comment by curiousleo** [comment] 2020-01-06 09:21
I'll take a look. My first guess is that `XDG_DATA_DIRS` is not set inside the environment created by `lorri`, but does exist within the environment created by `nix-shell`.

**Comment by curiousleo** [comment] 2020-01-06 12:04
I can't reproduce this right now: lorri builds `shell.nix` just fine for me.

> lorri 0.1.0
> nix (Nix) 2.3.1

I have:
```console
$ nix --version
nix (Nix) 2.3.1
$ lorri info
lorri version: 1
[...]
```

Where did you get "lorri 0.1.0" from?

**Comment by Profpatsch** [comment] 2020-03-03 12:02
Closing because no reply. Feel free to reopen.

**Closed by Profpatsch** 2020-03-03 12:02 UTC

**Comment by loewenheim** [comment] 2020-06-04 21:43
I have the exact same problem.
```shell
❯ nix --version
nix (Nix) 2.3.5
❯ lorri --version
lorri 1.0.0
```
I’m using `nixos-unstable` and installed `lorri` via `services.lorri.enable = true` in `configuration.nix`. If `shell.nix` contains "vulkan-validation-layers" and I run `lorri shell`, then …
```shell
❯ lorri shell
lorri: building environment.... done
Jun 04 23:40:47.860 ERRO Build failed. Hint: try running `lorri shell --cached` to use the most recent environment that was built successfully.
Build error: Nix process returned exit code 100.
$ "nix-build" "--out-link" "/tmp/.tmpWNM00O/result" "--" "/tmp/.tmp35G2r3/result"
these derivations will be built:
  /nix/store/3pjw8d1drlqcndv0m553jv7l7z70rgga-lorri-wrapped-project-env.drv
building '/nix/store/3pjw8d1drlqcndv0m553jv7l7z70rgga-lorri-wrapped-project-env.drv'...
/nix/store/ayj103h2q1x0kvzipl5vz5s4ycajh8fq-vulkan-validation-layers-1.2.131.2/nix-support/setup-hook: line 1: XDG_DATA_DIRS: unbound variable
builder for '/nix/store/3pjw8d1drlqcndv0m553jv7l7z70rgga-lorri-wrapped-project-env.drv' failed with exit code 1
error: build of '/nix/store/3pjw8d1drlqcndv0m553jv7l7z70rgga-lorri-wrapped-project-env.drv' failed
```

**Comment by Profpatsch** [comment] 2020-06-05 14:38
Is it possible to reduce this to a minimal `shell.nix` with only `vulkan-validation-layers` as input?

**Comment by loewenheim** [comment] 2020-06-05 17:25
Yeah, it works for me.
```shell
~
❯ mkdir lorri-test

~ 
❯ cd lorri-test/

~/lorri-test 
❯ lorri init
Jun 05 19:17:16.425 INFO wrote file, path: ./shell.nix
Jun 05 19:17:16.426 INFO wrote file, path: ./.envrc
Jun 05 19:17:16.426 INFO done
direnv: error /home/loewenheim/lorri-test/.envrc is blocked. Run `direnv allow` to approve its content

~/lorri-test 
❯ direnv allow
direnv: loading ~/lorri-test/.envrc
Jun 05 19:17:24.369 INFO lorri has not completed an evaluation for this project yet, expr: /home/loewenheim/lorri-test/shell.nix
direnv: export +IN_NIX_SHELL

#Edit shell.nix to add vulkan-validation-layers
~/lorri-test via ❄️  impure 
❯ kak shell.nix
direnv: loading ~/lorri-test/.envrc
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +HOST_PATH +IN_NIX_SHELL +LD +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_x86_64_unknown_linux_gnu_TARGET_HOST +NIX_BUILD_CORES +NIX_BUILD_TOP +NIX_CC +NIX_CC_WRAPPER_x86_64_unknown_linux_gnu_TARGET_HOST +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_INDENT_MAKE +NIX_LDFLAGS +NIX_LOG_FD +NIX_STORE +NM +OBJCOPY +OBJDUMP +RANLIB +READELF +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +allowSubstitutes +buildInputs +builder +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +extraClosure +name +nativeBuildInputs +nobuildPhase +origArgs +origBuilder +origExtraClosure +origOutputs +origPATH +origSystem +out +outputs +patches +phases +preHook +preferLocalBuild +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH

~/lorri-test via ❄️  impure took 13s 
❯ lorri shell
lorri: building environment.... done
Jun 05 19:17:57.268 ERRO Build failed. Hint: try running `lorri shell --cached` to use the most recent environment that was built successfully.
Build error: Nix process returned exit code 100.
$ "nix-build" "--out-link" "/tmp/.tmptjPwWV/result" "--" "/tmp/.tmprBGgs4/result"
these derivations will be built:
  /nix/store/9qmka5mxp86sw3cjdr9c7gbszkxm890n-lorri-wrapped-project-nix-shell.drv
building '/nix/store/9qmka5mxp86sw3cjdr9c7gbszkxm890n-lorri-wrapped-project-nix-shell.drv'...
/nix/store/8smyq4zy5d5ya16bym9b3lpi0a7sx3hb-vulkan-validation-layers-1.2.131.2/nix-support/setup-hook: line 1: XDG_DATA_DIRS: unbound variable
builder for '/nix/store/9qmka5mxp86sw3cjdr9c7gbszkxm890n-lorri-wrapped-project-nix-shell.drv' failed with exit code 1
error: build of '/nix/store/9qmka5mxp86sw3cjdr9c7gbszkxm890n-lorri-wrapped-project-nix-shell.drv' failed

~/lorri-test via ❄️  impure 
❯ cat shell.nix
let
  pkgs = import <nixpkgs> {};
in
pkgs.mkShell {
  buildInputs = [
    pkgs.vulkan-validation-layers
  ];
}
```

**Comment by Profpatsch** [comment] 2020-06-08 09:41
`vulkan-validation-layers` sets up a strange `setupHook` which fails if you
are in a pure shell environment:

```
> nix-shell --pure tmp/shell.nix
bash: XDG_DATA_DIRS: unbound variable
```

I’d report this as an upstream bug to the person that added that:

https://github.com/NixOS/nixpkgs/blob/b56c66e7e8565b16a4964840ef40243e07f78e84/pkgs/development/tools/vulkan-validation-layers/default.nix#L22-L25
