### ISSUE TITLE
Unwrap panic

### ISSUE THREAD

**Issue by tomberek** [target/lorri#66] opened 2019-04-25 14:40 UTC
Running on Ubuntu (via nix-review for the nixpkgs PR) and ran into this. There is plenty of space on the device.

https://github.com/NixOS/nixpkgs/pull/60211
```
lorri watch
Started
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Unrecoverable(Notify(Io(Os { code: 28, kind: Other, message: "No space left on device" })))', src/libcore/result.rs:997:5
stack backtrace:
   0:     0x5651e5047b6f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h0783754d3fee6459
   1:     0x5651e5057977 - std::sys_common::backtrace::print::h3122233e347d34d5
   2:     0x5651e504b153 - std::panicking::default_hook::{{closure}}::h5dd267379284318d
   3:     0x5651e504aed3 - std::panicking::default_hook::h91865806e9bd29bc
   4:     0x5651e504b84f - std::panicking::rust_panic_with_hook::hb03b843366405f92
   5:     0x5651e504b3e1 - std::panicking::continue_panic_fmt::h55006de900d00bf9
   6:     0x5651e504b2c5 - rust_begin_unwind
   7:     0x5651e507805c - core::panicking::panic_fmt::h86b59874e6b77e96
   8:     0x5651e4efd5cd - core::result::unwrap_failed::ha54ccda9a5abc9c9
   9:     0x5651e4f057ba - lorri::build_loop::BuildLoop::forever::he31eedd0e9c48593
  10:     0x5651e4eee859 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9ca173341b3c72e9
  11:     0x5651e4eef458 - std::panicking::try::do_call::ha3006f6b706ee83b
  12:     0x5651e5061c09 - __rust_maybe_catch_panic
  13:     0x5651e4f1d267 - <F as alloc::boxed::FnBox<A>>::call_box::h019709e300d681a2
  14:     0x5651e504693d - std::sys_common::thread::start_thread::hf9c1221451dff292
  15:     0x5651e50511b5 - std::sys::unix::thread::Thread::new::thread_start::h34e50d5a3156c212
  16:     0x7fc9261c8ef6 - start_thread
  17:     0x7fc925ee822e - __GI___clone
  18:                0x0 - <unknown>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:997:5
stack backtrace:
   0:     0x5651e5047b6f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h0783754d3fee6459
   1:     0x5651e5057977 - std::sys_common::backtrace::print::h3122233e347d34d5
   2:     0x5651e504b153 - std::panicking::default_hook::{{closure}}::h5dd267379284318d
   3:     0x5651e504aed3 - std::panicking::default_hook::h91865806e9bd29bc
   4:     0x5651e504b84f - std::panicking::rust_panic_with_hook::hb03b843366405f92
   5:     0x5651e504b3e1 - std::panicking::continue_panic_fmt::h55006de900d00bf9
   6:     0x5651e504b2c5 - rust_begin_unwind
   7:     0x5651e507805c - core::panicking::panic_fmt::h86b59874e6b77e96
   8:     0x5651e4efd534 - core::result::unwrap_failed::h92869f304e469b67
   9:     0x5651e4f0724a - lorri::ops::watch::main::hd6aa0621e18e8188
  10:     0x5651e4ede961 - lorri::main::hb735b843cfb29abb
  11:     0x5651e4edf282 - std::rt::lang_start::{{closure}}::h6844233bb9b63cd0
  12:     0x5651e504b262 - std::panicking::try::do_call::h11736d510a2ae4e6
  13:     0x5651e5061c09 - __rust_maybe_catch_panic
  14:     0x5651e505ca9d - std::rt::lang_start_internal::h483ed2ec71424c9f
  15:     0x5651e4edf274 - main
  16:     0x7fc925e17b8d - __libc_start_main
  17:     0x5651e4ede2c9 - _start
  18:                0x0 - <unknown>
```

**Comment by Profpatsch** [comment] 2019-04-25 15:49
This looks like either there *was* no space left on device (maybe you were looking at the wrong device and e.g. your /tmp tmpfs was full) or the watcher library has a bug.

I’m not sure what we can do without a way to reproduce here. As you can see it’s clearly marked as unrecoverable error by lorri.

**Comment by tomberek** [comment] 2019-04-25 15:55
Possibility that nix-review has a non-standard TMPDIR in an attempt to
sandbox.

**Comment by Profpatsch** [comment] 2019-04-25 16:56
Ah, uh, oh. Now I see the PR. We don’t want to put lorri into nixpkgs yet.

**Closed** 2019-04-25 17:04 UTC
Labels: more data needed
